# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bab82d9ffda934057b6814f88fcf0a82c0c4a6adf1c5e96f35415951d047a5bb7fdb324eef8d258157822000f062425297ee9c5a59885b63f8bbaafd347f98c4

test:
  secret_key_base: 72dbd2d43032f5c7bdd07cf9ea9343d8ebd3ae591c5049c4fdff8fcdea30edea6757b8cf526419095ea759fdf37ae93d856f528646b75c097a7791e163a5f73d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
